#!/usr/bin/env bash
# Script that displays School 10 times,  with for the 9th iteration Best School and then Hi on a new line

i=0
while [ $i -le 9 ]
do
	echo "Best School"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	((i++))
done
